CREATE TABLE IF NOT EXISTS `member_customers` (
  `customer_id` int(11) NOT NULL AUTO_INCREMENT COMMENT '顧客ID',
  `customer_code` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '顧客管理コード',
  `sei` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '名前（姓）',
  `mei` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '名前（名）',
  `sei_kana` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'カナ（姓）',
  `mei_kana` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'カナ（名）',
  `zip1` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '郵便番号1',
  `zip2` varchar(4) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '郵便番号2',
  `pref_id` int(11) DEFAULT NULL COMMENT '都道府県ID',
  `address1` varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '住所1',
  `address2` varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '住所2',
  `tel1` varchar(6) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '電話番号1',
  `tel2` varchar(6) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '電話番号2',
  `tel3` varchar(6) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '電話番号3',
  `mobile1` varchar(6) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '携帯電話番号1',
  `mobile2` varchar(6) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '携帯電話番号2',
  `mobile3` varchar(6) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '携帯電話番号3',
  `email` varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'メールアドレス',
  `email_mobile` varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '携帯メールアドレス',
  `url` varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'ホームページのURL',
  `login_id` varchar(200) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '会員認証ID',
  `password` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '会員認証パスワード',
  `sex` int(1) DEFAULT NULL COMMENT '性別',
  `job` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '職業',
  `birthday` date DEFAULT NULL COMMENT '生年月日',
  `type_id` int(11) DEFAULT NULL COMMENT '顧客種別ID',
  `status_id` int(11) DEFAULT NULL COMMENT '顧客ステータスID',
  `comment1` varchar(2048) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'コメント1',
  `comment2` varchar(2048) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'コメント2',
  `comment3` varchar(2048) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'コメント3',
  `point` int(11) DEFAULT '0' COMMENT 'ポイント',
  `magazin_flg` tinyint(1) DEFAULT '0' COMMENT 'メールマガジン購読フラグ',
  `active_flg` tinyint(1) NOT NULL DEFAULT '1' COMMENT '有効フラグ',
  `create_time` datetime NOT NULL COMMENT 'データ作成日時',
  `update_time` datetime NOT NULL COMMENT 'データ最終更新日時',
  `delete_flg` tinyint(1) NOT NULL COMMENT '削除フラグ',
  PRIMARY KEY (`customer_id`),
  KEY `email` (`email`),
  KEY `email_mobile` (`email_mobile`),
  KEY `customer_code` (`customer_code`),
  KEY `customer_type` (`type_id`),
  KEY `status_id` (`status_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='顧客テーブル';
